#!/usr/bin/env python
import os


libname = "demo_gdextension"
projectdir = "../project"

# =================================================================================
# localEnv
localEnv = Environment(tools=["default"], PLATFORM="")
customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]
opts = Variables(customs, ARGUMENTS)
# example:
# opts.Add(
#     BoolVariable(
#         key="compiledb",
#         help="Generate compilation DB (`compile_commands.json`) for external tools",
#         default=env.get("compiledb", False),
#     )
# )
opts.Update(localEnv)
Help(opts.GenerateHelpText(localEnv))

# =================================================================================
# 拷贝godot-cpp构建, 并与其共享env
env = localEnv.Clone()
env = SConscript("../../godot-cpp/SConstruct", {"env": env, "customs": customs})

# =================================================================================
# 自定义methods
import SConstruct_compiler_warning
# example: 
# env.__class__.disable_warnings = SConstruct_compiler_warning.disable_warnings

# =================================================================================
# 添加include path
env.Append(CPPPATH=["."])

# =================================================================================
# 编译'gdextension'目录下所有.cpp文件
sources = []
for root, dirs, files in os.walk('.'):
    for f in files:
        if f.endswith('.cpp'):
            sources.append(root + '/' + f)

# =================================================================================
# compiler warnings
# FIXME: https://github.com/godotengine/godot-cpp/pull/1007
opts.Add(EnumVariable("warnings", "Level of compilation warnings", "all", ("extra", "all", "moderate", "no")))
opts.Add(BoolVariable("werror", "Treat compiler warnings as errors", False))
opts.Update(env)
SConstruct_compiler_warning.set_compiler_warnings(env)

# =================================================================================
# doc
# if env["target"] in ["editor", "template_debug"]:
#     try:
#         doc_data = env.GodotCPPDocData("gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
#         sources.append(doc_data)
#     except AttributeError:
#         print("Not including class reference as we're targeting a pre-4.3 baseline.")


# =================================================================================
# library
file = "{}{}{}".format(libname, env["suffix"], env["SHLIBSUFFIX"])

# macos/ios
# if env["platform"] == "macos" or env["platform"] == "ios":
#     platlibname = "{}.{}.{}".format(libname, env["platform"], env["target"])
#     file = "{}.framework/{}".format(env["platform"], platlibname, platlibname)

libraryfile = "bin/{}/{}".format(env["platform"], file)
library = env.SharedLibrary(
    libraryfile,
    source=sources,
)

copy = env.InstallAs("{}/bin/{}/{}".format(projectdir, env["platform"], file), library)

default_args = [library, copy]
env.Default(*default_args)
